### ISSUE TITLE
Always get core dumped！

### ISSUE THREAD

**Issue by b224hisl** [uvahotspot/HotSpot#9]
Hello，I can finish the **example3** successfully, but when I would like to simulate my design, it always get core dumped, as shown here. I just modify my floorplan files and trace files and leave other file unchanged in example3, I don't know why it happens
```
⦗OSS CAD Suite⦘ root@server1:/Thermal_sim/HotSpot/examples/example3# sh run.sh 
mkdir: cannot create directory 'outputs': File exists
Parsing input files...
Creating thermal circuit...
Segmentation fault (core dumped)
cp: cannot stat 'outputs/example.steady': No such file or directory
Parsing input files...
Creating thermal circuit...
Segmentation fault (core dumped)
Traceback (most recent call last):
  File "../../scripts/split_grid_steady.py", line 27, in <module>
    with open(grid_steady_file, "r") as ifp:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/example.grid.steady'
QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-root'
Traceback (most recent call last):
  File "../../scripts/grid_thermal_map.py", line 76, in <module>
    with open(temperatures_filename, "r") as fp:
FileNotFoundError: [Errno 2] No such file or directory: 'outputs/example_layer2.grid.steady'
```
I have checked my floorplan files and trace filecarefully,I have uploaded my configuration here. Could anyone help me to see what's wrong?

**floorplan1.flp:**
```
# Floorplan close to the Alpha EV6 processor
# Line Format: <unit-name>\t<width>\t<height>\t<left-x>\t<bottom-y>
# all dimensions are in meters
# comment lines begin with a '#'
# comments and empty lines are ignored

grid1_1	0.001300 	0.000733 	0.000000 	0.001487 
grid1_2	0.000620 	0.000733 	0.001300 	0.001487 
grid1_3	0.001300 	0.000733 	0.001920 	0.001487 
grid1_4	0.001300 	0.001487 	0.000000 	0.000000 
grid1_5	0.000620 	0.001487 	0.001300 	0.000000 
grid1_6	0.001300 	0.001487 	0.001920 	0.000000
```
**floorplan2.flp:**
```
# Floorplan close to the Alpha EV6 processor
# Line Format: <unit-name>\t<width>\t<height>\t<left-x>\t<bottom-y>
# all dimensions are in meters
# comment lines begin with a '#'
# comments and empty lines are ignored

grid2_1 0.001100    0.000809 	0.000000 	0.001411 
grid2_2	0.001020 	0.000809 	0.001100 	0.001411 
grid2_3	0.001100 	0.000809 	0.002120 	0.001411 
grid2_4	0.001100 	0.000611 	0.000000 	0.000800 
grid2_5	0.001020 	0.000611 	0.001100 	0.000800 
grid2_6	0.001100 	0.000611 	0.002120 	0.000800 
grid2_7	0.001100 	0.000800 	0.000000 	0.000000 
grid2_8	0.001020 	0.000800 	0.001100 	0.000000 
grid2_9	0.001100 	0.000800 	0.002120 	0.000000
```
**example.ptrace:**
```
grid1_1 grid1_2 grid1_3 grid1_4 grid1_5 grid1_6 grid2_1 grid2_2 grid2_3 grid2_4 grid2_5 grid2_6 grid2_7 grid2_8 grid2_9
10.0	25.0	15.0	1.44	7.37	1.44	8.27	14.3	4.55	0.179	1.24	0.775	1.33	0.0471	1.07
10.0	25.0	15.0	0.963	4.92	0.963	5.4	8.91	2.91	0.111	0.827	0.514	0.885	0.0368  0.693
```

**Comment by hwpeng** [comment]
Add a blank line to each .flp and .ptrace file and it should work.

I'm not the author, I just met a similar issue and this is how I solved it.

**Comment by yyan7223** [comment]
Have you addressed this issue? @b224hisl

**Comment by yyan7223** [comment]
I figure it out! The maximum and minimum floorplan margin of different layers must be the same, and there should be no physical gaps between units.

**Comment by Jian-PENG207** [comment]
> I figure it out! The maximum and minimum floorplan margin of different layers must be the same, and there should be no physical gaps between units.

Hello, could you explain more about  the margin and physical gaps? I am also facing this problem
